### ISSUE TITLE
Server error on note creation and deletion 

### ISSUE THREAD

**Issue by skllcrn** [notebase/notebase-issues#1]
When attempting to delete a note: 

"There was a problem communicating with the server, please reload the page."

...after a few seconds the page reloads and displays: 

"Sync timeout

The server did not report successfully saving your changes in a timely manner. Changes made in the last 30 seconds may not have been saved.

This can sometimes happen if there is a network problem or a problem with our servers. It is usually temporary.

You should reload the page to avoid further data loss. We apologize for the inconvenience." 

Currently getting the same issue when adding a new line... Haven't seen that one before!

**Comment by stiang** [comment]
Fixed!
